- name: iptables in Ansible
  hosts: all
  tasks:
    - name: allow established and related connection
      iptables:
        chain: Input
        ctstate: ESTABLISHED, RELATED
        jump: ACCEPT
      become: yes

    - name: add rule number 5
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        jump: ACCEPT
        rule_num: 5
    
    - name: policy drop
      iptables:
        chain: INPUT
        policy: DROP
        